// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package Exchange

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExchangeDataClient is the client API for ExchangeData service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExchangeDataClient interface {
	Exchange(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type exchangeDataClient struct {
	cc grpc.ClientConnInterface
}

func NewExchangeDataClient(cc grpc.ClientConnInterface) ExchangeDataClient {
	return &exchangeDataClient{cc}
}

func (c *exchangeDataClient) Exchange(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/Exchange.ExchangeData/exchange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExchangeDataServer is the server API for ExchangeData service.
// All implementations must embed UnimplementedExchangeDataServer
// for forward compatibility
type ExchangeDataServer interface {
	Exchange(context.Context, *Request) (*Reply, error)
	mustEmbedUnimplementedExchangeDataServer()
}

// UnimplementedExchangeDataServer must be embedded to have forward compatible implementations.
type UnimplementedExchangeDataServer struct {
}

func (UnimplementedExchangeDataServer) Exchange(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exchange not implemented")
}
func (UnimplementedExchangeDataServer) mustEmbedUnimplementedExchangeDataServer() {}

// UnsafeExchangeDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExchangeDataServer will
// result in compilation errors.
type UnsafeExchangeDataServer interface {
	mustEmbedUnimplementedExchangeDataServer()
}

func RegisterExchangeDataServer(s grpc.ServiceRegistrar, srv ExchangeDataServer) {
	s.RegisterService(&ExchangeData_ServiceDesc, srv)
}

func _ExchangeData_Exchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeDataServer).Exchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Exchange.ExchangeData/exchange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeDataServer).Exchange(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// ExchangeData_ServiceDesc is the grpc.ServiceDesc for ExchangeData service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExchangeData_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Exchange.ExchangeData",
	HandlerType: (*ExchangeDataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "exchange",
			Handler:    _ExchangeData_Exchange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/interface.proto",
}
